<script context="module">
  export const NEIGHBOURING_STATES = {'Alaska':['Northwest Territory', 'Alberta', 'Kamchatka'],
            'Northwest Territory':['Alaska', 'Greenland', 'Alberta', 'Ontario'],
            'Alberta':['Northwest Territory', 'Alaska', 'Ontario', 'Western United States'],
            'Ontario':['Alberta', 'Northwest Territory', 'Greenland', 'Quebec', 'Western United States', 'Eastern United States'],
            'Quebec':['Greenland', 'Ontario', 'Eastern United States'],
            'Western United States':['Alberta', 'Ontario', 'Eastern United States', 'Central America'],
            'Eastern United States':['Western United States', 'Quebec', 'Ontario', 'Central America'],
            'Central America':['Venezuela', 'Eastern United States', 'Western United States'],
            'Greenland':['Iceland', 'Northern Territory', 'Ontario', 'Quebec'],
            'Afghanistan':['Ukraine', 'Ural', 'China', 'India', 'Middle East'],
            'Middle East':['Southern Europe', 'Egypt', 'India', 'Afghanistan', 'Ukraine'],
            'India':['Middle East', 'China', 'Afghanistan', 'Siam'],
            'Siam':['India', 'China', 'Indonesia'],
            'China':['Mongolia', 'Siam', 'India', 'Afghanistan', 'Ural', 'Siberia'],
            'Mongolia':['Japan', 'Kamchatka', 'Irkutsk', 'Siberia', 'China'],
            'Irkutsk':['Siberia', 'Yakutsk', 'Kamchatka', 'Mongolia'],
            'Yakutsk':['Siberia', 'Irkutsk', 'Kamchatka'],
            'Kamchatka':['Yakutsk', 'Irkutsk', 'Mongolia', 'Japan', 'Alaska'],
            'Japan':['Kamchatka', 'Mongolia'],
            'Siberia':['Ural', 'Yakutsk', 'Irkutsk', 'Mongolia', 'China'],
            'Ural':['Ukraine', 'Afghanistan', 'China', 'Siberia'],
            'Iceland':['Greenland', 'Scandinavia', 'Great Britain'],
            'Scandinavia':['Northern Europe', 'Britain', 'Ukraine', 'Iceland'],
            'Britain':['Western Europe', 'Northern Europe', 'Scandinavia', 'Iceland'],
            'Western Europe':['Great Britain', 'North Africa', 'Southern Europe', 'Northern Europe'],
            'Northern Europe':['Western Europe', 'Southern Europe', 'Ukraine', 'Great Britain', 'Scandinavia'],
            'Southern Europe':['Middle East', 'Egypt', 'North Africa', 'Western Europe', 'Northern Europe', 'Ukraine'],
            'Ukraine':['Afghanistan', 'Ural', 'Scandinavia', 'Northern Europe', 'Southern Europe', 'Middle East'],
            'North Africa':['Brazil', 'Congo', 'East Africa', 'Egypt', 'Southern Europe', 'Western Europe'],
            'Egypt':['Middle East', 'Southern Europe', 'North Africa', 'East Africa'],
            'East Africa':['Madagascar', 'South Africa', 'Congo', 'North Africa', 'Egypt'],
            'Congo':['South Africa', 'East Africa', 'North Africa'],
            'South Africa':['East Africa', 'Congo', 'Madagascar'],
            'Madagascar':['South Africa', 'East Africa'],
            'Venezuela':['Brazil', 'Peru', 'Central America'],
            'Peru':['Brazil', 'Argentina', 'Venezuela'],
            'Brazil':['North Africa', 'Venezuela', 'Peru', 'Argentina'],
            'Argentina':['Brazil', 'Peru'],
            'Indonesia':['Western Australia', 'New Guinea', 'Siam'],
            'New Guinea':['Western Australia', 'Eastern Australia', 'Indonesia'],
            'Eastern Australia':['Western Australia', 'New Guinea'],
            'Western Australia':['Indonesia', 'New Guinea', 'Eastern Australia']};
</script>
